basePath: /api/v1
info:
  contact: {}
  description: This API contains the source for the LOG-MINDER  app
  title: LOG-MINDER APPLICATION API DOCUMENTATION
paths: {}
securityDefinitions:
  UsersAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
